### ISSUE TITLE
wong file on the kde.store page

### ISSUE THREAD

**Issue by bird-dancer** [Mrcuve0/Aritim-Dark#16]
I am sorry if this does not belong here but I don't know where else to put this. But since the last commit, you can only download the ArithimLight.colors file from the  [kde.store](https://store.kde.org/p/1280295l) site.

**Comment by Mrcuve0** [comment]
Don't worry you did good, this is probably the best way to reach me! :D

And indeed, thank you for letting me know! I'm terrible at updating things here and there, I'm always making mistakes. I'm fixing it right now, sorry!

**Comment by Mrcuve0** [comment]
Fixed! Thank you once again!

You may want to wait approx. 30 minutes before downloading the correct version (I noticed KDE Store has some cache latency when upgrading files)

**Comment by bird-dancer** [comment]
Works now thank you. And thank you for the great theme.
