### ISSUE TITLE
Konsole color scheme source code location?

### ISSUE THREAD

**Issue by tnyeanderson** [Mrcuve0/Aritim-Dark#21]
**Is your feature request related to a problem? Please describe.**
Source code location for the [Konsole color scheme](https://www.pling.com/p/1283010/) is not apparent

**Describe the solution you'd like**
A link to the git repo where the color scheme file for Konsole is maintained :)

**Describe alternatives you've considered**
None, Aritim-Dark is the best theme!

**Additional context**
Thank you for your hard work on this theme, it is my daily driver and will continue to be!!

**Comment by Mrcuve0** [comment]
Hi and thank you for your kind words! I really appreciate.
At the time I uploaded it I thought the `.colorscheme` file the user downloads from the site would suffice.

But yeah, you are right, it's better to link the file in the repo, it's simply better organized. Thanks for letting me know, have a nice day!

**Comment by tnyeanderson** [comment]
Thanks for the quick response! But it looks like you added the `.profile` instead of the actual `.colorscheme` file that gets placed in `.local/share/konsole/Aritim Dark.colorscheme`... If you could add *that* file to this repo I would be super grateful! And as always, thanks again for your hard work on this :)

**Comment by Mrcuve0** [comment]
You're right, I'm completely off these days ahaha, thanks once again! Uploading it right now

**Comment by Mrcuve0** [comment]
PS: Also for Aritim-Light
