### ISSUE TITLE
Mouseover tooltips washed out...

### ISSUE THREAD

**Issue by derek-shnosh** [Mrcuve0/Aritim-Dark#23]
**Describe the bug**
While hovering over items in the panel, information is washed out if the object behind the tooltip is lightly colored.

**To Reproduce**
Mouse over items in the panel with a white/grey background/wallpaper.

**Screenshots**
![ksnip_20211228-165504](https://user-images.githubusercontent.com/21090563/147615772-18260c35-6a8b-432a-a7ae-dea6df1cea44.png)
![ksnip_20211228-170228](https://user-images.githubusercontent.com/21090563/147615845-1f0fdb8b-e1b9-463c-ac96-2c668225a3c0.png)

**Desktop (additional informations):**
 - OS: Kubuntu 21.10
 - KDE Plasma Version: 5.23.4
 - KDE Frameworks Version: 5.89.0

**Additional context**
None.

**Comment by Mrcuve0** [comment]
Thanks for your feedback. I'm aware of the issue and tried to circumvent it multiple times. Sadly it's quite hard to find a sweet spot among transparency and readability with white-ish backgrounds. Moreover, testing different combinations to highlight readability issues can be very time consuming. As for now I have very limited time (or no time at all) to side projects such as themes :disappointed: 

If you want to try solve it yourself, you can tweak the `[ContrastEffect]` parameters in the following file and see if you can find the best configuration for you: `/home/$USER/.local/share/plasma/desktoptheme/<THEME_NAME_HERE>` or modify the `background.svg` and `panel.svg` files. You can also try to do both modifications and find your sweet spot. I'd be glad to include your findings!

Thank you for reporting the issue and for your patience, wishing you a wonderful day and happy new year in advance!

**Comment by Mrcuve0** [comment]
I'm uploading a new version of the theme to the KDE Store. I tested it against various white backgrounds and should be way better than before. 

It may not be available for quite some time (hours, speaking form experience) due to various cache issues from the web store itself. If you want to try it immediately, unzip the attached file in the aforementioned folder and restart plasmashell `plasmashell --replace &`

Let me know what you think!

[Aritim-Dark-Rounded-Blur.zip](https://github.com/Mrcuve0/Aritim-Dark/files/7789835/Aritim-Dark-Rounded-Blur.zip)

**Comment by derek-shnosh** [comment]
I received the update via Discover, looks like the hover tooltips are closely matched to the calendar/notifications; much easier to read now.

![ksnip_20211229-111221](https://user-images.githubusercontent.com/21090563/147691509-015970e0-47e3-464c-8891-cf9ae11b5f19.png)

I appreciate you taking the time to look into this and provide a fix, I stand by my original comment on pling...

![ksnip_20211229-111353](https://user-images.githubusercontent.com/21090563/147691597-5d60c3e7-bacb-4726-9e23-57cf313b09ee.png)

👊🏼👍🏼
