### ISSUE TITLE
Package does not install

### ISSUE THREAD

**Issue by ghost** [Mrcuve0/Aritim-Dark#4]
I tried installing the Look-and-Feel Theme on Fedora 30, but failed.

Going to System Settings --> Workspace Theme --> Get New Look-And-Feel Themes and choosing Aritim Dark theme, it lets me install, doesn't fail, but the theme doesn't appear in the main window so I can choose it.

Then I tried installing from CLI using kpackagetool5 method and failed with error:

```
# kpackagetool5 -i Aritim-Dark-KDE-master.zip
couldn't find knsrc file for "wallpaper.knsrc"
Error: Installation of /home/user/Downloads/Aritim-Dark-KDE-master.zip failed: Could not install dependency: 'kns://wallpaper.knsrc/api.kde-look.org/1291306'
```

Went and removed that dependency in the metadata.desktop file, but got the same error for the next dependency and so on. I was only able to install the package after I removed all dependencies.

Please fix the metadata.desktop file to point to the right dependencies.

**Comment by Mrcuve0** [comment]
Please take a look at this [related issue](https://github.com/Mrcuve0/Aritim-Light-KDE/issues/2).

This is a known bug. Briefly, you'll have to downgrade the `frameworkintegration 5.58.1-1` package until a solution is found and a new version of the package is released.
The dependencies are all correct and this is not bug of the theme.

**Comment by Mrcuve0** [comment]
No feedback received so far, assuming the issue was solved. Closing the issue
