### ISSUE TITLE
Where are the window decorations?

### ISSUE THREAD

**Issue by UnicornsOnLSD** [Mrcuve0/Aritim-Dark#5]
I've installed this through KDE and can't find the window decorations anywhere. There is also no sign of them existing on the KDE store. Here's a screenshot: https://i.imgur.com/BEtbNfu.png

Is there anywhere I can download the window decorations?

**Comment by Mrcuve0** [comment]
You can find the link in the README of this repository, they are not on the KDE Store.
Here's the link --> https://github.com/ishovkun/SierraBreeze

**Comment by UnicornsOnLSD** [comment]
Thanks!
