### ISSUE TITLE
Is it possible to disable transparency on the toolbar?

### ISSUE THREAD

**Issue by UnicornsOnLSD** [Mrcuve0/Aritim-Dark#6]
The toolbar is blurry and I don't like how I can see my desktop through it. Is there a file I can edit which makes the toolbar opaque?

**Comment by Mrcuve0** [comment]
Hi! What are you looking for is actually referred as "Plasma Theme".
I just uploaded a non-blurred version of this theme on the KDE Store:

--> https://www.opendesktop.org/p/1312804/

It still need a little bit of polish (I'm a newbie of Inkscape), although it's usable.

There's no "string" to change the blurriness/opacity of a theme, as far I understood you have to edit directly the ```svg``` files.
Once installed, you can find this theme under the folders ```~/.local/share/plasma/desktoptheme/```

If you like the theme, you may want to leave a positive feedback on the KDE Store, this will help me a lot in the development!
