### ISSUE TITLE
Krita theme

### ISSUE THREAD

**Issue by Arisa-Snowbell** [Mrcuve0/Aritim-Dark#7]
The only theme that doesn't show in | **Settings** -> **Themes** | in program **Krita**, I was trying to fix it myself but without success.
I have no idea what the problem is, maybe some option that is missing in .colors?

**Comment by Mrcuve0** [comment]
Hi! I never used Krita so I don't know if it should automatically pick the theme used system-wide.
However, I managed to add Aritm Dark as a theme for Krita, it's a very easy task:

You just need to copy the ```AritimDark.colors``` file into Krita's theme folder.

You can find the original ```AritimDark.colors``` file following the ```~/.local/share/color-schemes/``` path.
Copy the file and paste it in the ```~/.local/share/krita/color-schemes/``` folder.
Relaunch Krita and change the theme by clicking on **Settings -> Themes** like you previously did.

Done!

Let me know if this helps so I can close the issue.
Finally, I'd be really thankful if you could leave a positive rating in the product page! https://store.kde.org/p/1281836/

**Comment by Arisa-Snowbell** [comment]
Thank you very much, I did not expect it to be so simple but it works, so once more thank you very much, the issue is solved.
